In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import matplotlib.cm as cm
# import cartopy.crs as ccrs
# import cartopy.feature as cfeature
import h5py
import random

In [7]:
test = h5py.File("train_fixed_25.hdf5",'r')
train = h5py.File("test_fixed_25.hdf5",'r')


In [10]:
b_test = test['truth']
b_train = train['truth']

In [11]:
b_test.shape

(56413, 16, 16)

In [13]:
b_train.shape

(2452, 16, 16)

In [15]:
# test of is in
t1 = np.array([0,1,2,3,4,5,6,7]).reshape(2,2,2)

In [31]:
t2 = np.array([0,1,2,3]).reshape(2,2)

In [32]:
print(t1)
print(t2)
t3 = np.array([1,0,2,3]).reshape(2,2)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
[[0 1]
 [2 3]]


In [39]:
t3.tolist() in t1.tolist()


False

In [44]:
for i in range(10000):
    for j in range(2452):
        if (b_test[j] == b_train[i]).all():
            print("same:  " + str(i))
        
        

same:  7
same:  12
same:  20
same:  46
same:  46
same:  55
same:  82
same:  96
same:  123
same:  128
same:  129
same:  147
same:  151
same:  155
same:  158
same:  159
same:  168
same:  173
same:  175
same:  184
same:  187
same:  211
same:  218
same:  220
same:  227
same:  243
same:  249
same:  254
same:  287
same:  293
same:  308
same:  326
same:  328
same:  333
same:  346
same:  350
same:  352
same:  357
same:  359
same:  361
same:  363
same:  364
same:  366
same:  368
same:  371
same:  372
same:  377
same:  380
same:  381
same:  383
same:  387
same:  392
same:  398
same:  405
same:  407
same:  413
same:  424
same:  430
same:  436


KeyboardInterrupt: 