In [1]:
import numpy as np
import h5py
import matplotlib.pyplot as plt

In [11]:
dataset = h5py.File('train_next_event.hdf5','r')


In [12]:
dataset['truth'].shape

(57893, 16, 16)

In [14]:
a = dataset['truth']
b = a[0:2]

In [5]:
b

array([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 1., 1., 0., 0

In [15]:
c = np.sum(a, axis = 0)

In [16]:
c

array([[ 957., 1090., 1215., 1188., 1361., 1266., 1344., 1339., 1377.,
        1303., 1245., 1209., 1173., 1021.,  884.,  758.],
       [1045., 1283., 1421., 1456., 1567., 1529., 1613., 1554., 1522.,
        1572., 1493., 1402., 1397., 1269., 1142.,  958.],
       [1091., 1398., 1558., 1584., 1611., 1645., 1720., 1781., 1689.,
        1700., 1606., 1512., 1484., 1426., 1284., 1022.],
       [1261., 1469., 1548., 1693., 1775., 1792., 1760., 1820., 1808.,
        1811., 1710., 1716., 1651., 1481., 1346., 1137.],
       [1264., 1450., 1598., 1702., 1700., 1815., 1888., 1887., 1831.,
        1891., 1799., 1731., 1755., 1608., 1426., 1177.],
       [1226., 1428., 1581., 1693., 1784., 1833., 1860., 1921., 1989.,
        1841., 1878., 1775., 1663., 1561., 1458., 1145.],
       [1266., 1496., 1592., 1677., 1769., 1895., 1893., 1877., 1955.,
        1928., 1862., 1818., 1713., 1628., 1448., 1190.],
       [1240., 1511., 1585., 1694., 1753., 1867., 1867., 1884., 1961.,
        1885., 1801., 1752

In [17]:
multiplicative_factors = (len(a)  - c)// c


In [18]:
multiplicative_factors

array([[59., 52., 46., 47., 41., 44., 42., 42., 41., 43., 45., 46., 48.,
        55., 64., 75.],
       [54., 44., 39., 38., 35., 36., 34., 36., 37., 35., 37., 40., 40.,
        44., 49., 59.],
       [52., 40., 36., 35., 34., 34., 32., 31., 33., 33., 35., 37., 38.,
        39., 44., 55.],
       [44., 38., 36., 33., 31., 31., 31., 30., 31., 30., 32., 32., 34.,
        38., 42., 49.],
       [44., 38., 35., 33., 33., 30., 29., 29., 30., 29., 31., 32., 31.,
        35., 39., 48.],
       [46., 39., 35., 33., 31., 30., 30., 29., 28., 30., 29., 31., 33.,
        36., 38., 49.],
       [44., 37., 35., 33., 31., 29., 29., 29., 28., 29., 30., 30., 32.,
        34., 38., 47.],
       [45., 37., 35., 33., 32., 30., 30., 29., 28., 29., 31., 32., 32.,
        34., 38., 47.],
       [45., 38., 35., 32., 31., 28., 29., 28., 28., 29., 30., 30., 32.,
        35., 39., 45.],
       [44., 40., 36., 33., 32., 31., 29., 29., 28., 29., 30., 31., 32.,
        34., 35., 45.],
       [47., 39., 35., 33., 31

In [8]:
np.save("new_event_weights", multiplicative_factors)

In [9]:
%pwd

'/rdsgpfs/general/user/gcl15/home/masters_project/data'

In [19]:
dataset.close()